//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionesInteligentes.Colef.Sia.Core.NHibernateValidator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpanishValidatorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpanishValidatorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DecisionesInteligentes.Colef.Sia.Core.NHibernateValidator.SpanishValidatorMessage" +
                            "s", typeof(SpanishValidatorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aserción fallida.
        /// </summary>
        internal static string validator_assertFalse {
            get {
                return ResourceManager.GetString("validator.assertFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aserción fallida.
        /// </summary>
        internal static string validator_assertTrue {
            get {
                return ResourceManager.GetString("validator.assertTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credit card number.
        /// </summary>
        internal static string validator_creditCard {
            get {
                return ResourceManager.GetString("validator.creditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valor numérico fuera de rango (&lt;{integerDigits} digits&gt;.&lt;{fractionalDigits} digits&gt; era lo esperado).
        /// </summary>
        internal static string validator_digits {
            get {
                return ResourceManager.GetString("validator.digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid EAN.
        /// </summary>
        internal static string validator_ean {
            get {
                return ResourceManager.GetString("validator.ean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no es una dirección de correo electrónico bien formada.
        /// </summary>
        internal static string validator_email {
            get {
                return ResourceManager.GetString("validator.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe ser una fecha futura.
        /// </summary>
        internal static string validator_future {
            get {
                return ResourceManager.GetString("validator.future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN no válido.
        /// </summary>
        internal static string validator_iban {
            get {
                return ResourceManager.GetString("validator.iban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la longitud debe ser entre {Min} y {Max}.
        /// </summary>
        internal static string validator_length {
            get {
                return ResourceManager.GetString("validator.length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe ser menor o igual a {Value}.
        /// </summary>
        internal static string validator_max {
            get {
                return ResourceManager.GetString("validator.max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe ser mayor o igual a {Value}.
        /// </summary>
        internal static string validator_min {
            get {
                return ResourceManager.GetString("validator.min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no debe ser vacío.
        /// </summary>
        internal static string validator_notEmpty {
            get {
                return ResourceManager.GetString("validator.notEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe ser no nulo.
        /// </summary>
        internal static string validator_notNull {
            get {
                return ResourceManager.GetString("validator.notNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no debe ser nulo o vacío.
        /// </summary>
        internal static string validator_notNullNotEmpty {
            get {
                return ResourceManager.GetString("validator.notNullNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe ser numérico.
        /// </summary>
        internal static string validator_numeric {
            get {
                return ResourceManager.GetString("validator.numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe ser una fecha pasada.
        /// </summary>
        internal static string validator_past {
            get {
                return ResourceManager.GetString("validator.past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe corresponder a &quot;{Regex}&quot;.
        /// </summary>
        internal static string validator_pattern {
            get {
                return ResourceManager.GetString("validator.pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe ser entre {Min} y {Max}.
        /// </summary>
        internal static string validator_range {
            get {
                return ResourceManager.GetString("validator.range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el tamaño debe ser entre {Min} y {Max}.
        /// </summary>
        internal static string validator_size {
            get {
                return ResourceManager.GetString("validator.size", resourceCulture);
            }
        }
    }
}
