insert into Estados values('Activo',null,GETDATE(),null,GETDATE(),1);
insert into Estados values('Baja',null,GETDATE(),null,GETDATE(),1);
insert into Estados values('Sabático',null,GETDATE(),null,GETDATE(),1);
insert into Estados values('Licencia c/ sueldo',null,GETDATE(),null,GETDATE(),1);
insert into Estados values('Licencia s/ sueldo',null,GETDATE(),null,GETDATE(),1);
insert into Estados values('Superación académica',null,GETDATE(),null,GETDATE(),1);

insert into GradoAcademicos values('Licenciatura',null,GETDATE(),null,GETDATE(),1);
insert into GradoAcademicos values('Maestría',null,GETDATE(),null,GETDATE(),1);
insert into GradoAcademicos values('Doctor',null,GETDATE(),null,GETDATE(),1);

insert into Categorias values('Titular A',null,GETDATE(),null,GETDATE(),1);
insert into Categorias values('Titular B',null,GETDATE(),null,GETDATE(),1);
insert into Categorias values('Titular C',null,GETDATE(),null,GETDATE(),1);
insert into Categorias values('Asociado A',null,GETDATE(),null,GETDATE(),1);
insert into Categorias values('Asociado B',null,GETDATE(),null,GETDATE(),1);
insert into Categorias values('Asociado C',null,GETDATE(),null,GETDATE(),1);

insert into Cargos values('Investigador',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Director de Departamento',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Director Regional',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Coordinador de Programa',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Presidente',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Secretario General Académico',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Coordinador de Departamento de Apoyo',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Coordinador de Oficinas de Enlace y Vinculación',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Director de Posgrado',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Director General de Vinculación y Apoyo Académico',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Director General Académico',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Becario de Alto Nivel',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Investigador por Proyecto',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Secretario General de Planeación y Desarrollo Institucional',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Direccion General de Administracion y Finanzas',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Direccion General Regional Noroeste',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Direccion de Area',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Otros',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Coordinador de Posgrado',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Coordinador de EcoParque',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Asistente de Director',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Estudiante Becario',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Investigador visitante',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Director General de Docencia',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Director General de Vinculación Institucional',null,GETDATE(),null,GETDATE(),1);
insert into Cargos values('Director General de Asuntos Académicos',null,GETDATE(),null,GETDATE(),1);

insert into SNIs values('Candidato',null,GETDATE(),null,GETDATE(),1);
insert into SNIs values('Nivel 1',null,GETDATE(),null,GETDATE(),1);
insert into SNIs values('Nivel 2',null,GETDATE(),null,GETDATE(),1);
insert into SNIs values('Nivel 3',null,GETDATE(),null,GETDATE(),1);
insert into SNIs values('Emerito',null,GETDATE(),null,GETDATE(),1);

insert into Sedes values('Matamoros','Dirección General Regional Noreste',null,GETDATE(),null,GETDATE(),1);
insert into Sedes values('Nuevo Laredo','Dirección General Regional Noreste',null,GETDATE(),null,GETDATE(),1);
insert into Sedes values('Piedras Negras','Dirección General Regional Noreste',null,GETDATE(),null,GETDATE(),1);
insert into Sedes values('Monterrey','Dirección General Regional Noreste',null,GETDATE(),null,GETDATE(),1);
insert into Sedes values('Ciudad Juarez','Dirección General Regional Noroeste',null,GETDATE(),null,GETDATE(),1);
insert into Sedes values('Tijuana','Tijuana',null,GETDATE(),null,GETDATE(),1);
insert into Sedes values('Mexicali','Dirección General Regional Noroeste',null,GETDATE(),null,GETDATE(),1);
insert into Sedes values('Nogales','Dirección General Regional Noroeste',null,GETDATE(),null,GETDATE(),1);

insert into TipoArticulos values('Artículo con arbitraje',null,GETDATE(),null,GETDATE(),1);
insert into TipoArticulos values('Artículo sin arbitraje',null,GETDATE(),null,GETDATE(),1);
insert into TipoArticulos values('Artículo traducido a otro idioma',null,GETDATE(),null,GETDATE(),1);

insert into Indices values('CLASE',null,GETDATE(),null,GETDATE(),1);
insert into Indices values('CONACYT',null,GETDATE(),null,GETDATE(),1);
insert into Indices values('DIALNET',null,GETDATE(),null,GETDATE(),1);
insert into Indices values('ECON-LIT',null,GETDATE(),null,GETDATE(),1);
insert into Indices values('HAPI',null,GETDATE(),null,GETDATE(),1);
insert into Indices values('HLAS',null,GETDATE(),null,GETDATE(),1);
insert into Indices values('IN-RECS',null,GETDATE(),null,GETDATE(),1);
insert into Indices values('ISI',null,GETDATE(),null,GETDATE(),1);
insert into Indices values('JSTOR',null,GETDATE(),null,GETDATE(),1);
insert into Indices values('LATINDEX',null,GETDATE(),null,GETDATE(),1);
insert into Indices values('RedAlyc',null,GETDATE(),null,GETDATE(),1);
insert into Indices values('Padrón anterior',null,GETDATE(),null,GETDATE(),1);
insert into Indices values('Indice no aprobado',null,GETDATE(),null,GETDATE(),1);
insert into Indices values('Sin índice',null,GETDATE(),null,GETDATE(),1);

insert into Instituciones values('Universidad Externado de Colombia',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Ayuntamiento de Matamoros',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('DIF Matamoros',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Casa de las Culturas del Mundo',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Mexicano de la Juventud',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro Universitario de Ciencias Sociales y Humanidades. Universidad de Guadalajara',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto de Investigaciones Jurídicas de la UNAM',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Organización Jóvenes Demócratas',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Producen',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Fuerza Aerea de Chile',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Secretaría  Plan del Desarrollo',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('UAM-Iztapalapa',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CEISAL',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('UABC MEXICALI',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Nacional Autónoma de México',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de York',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma Metropolitana - Azcapotzalco',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CREDAL',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('SOMDE, CONAPO, CRIM, UNFPA',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Organización Política Alemana Jóvenes Demócratas',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Veracruzana',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Michoacana de San Nicolás de Hidalgo',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Asociación Mexicana de Estudios del Trabajo','Oscar Contreras Montellanos',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Banco Interamericano de Desarrollo',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Tecnologico de Piedras Negras',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Tecnológica Centroamericana (Honduras)',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('The University of Califronia and The COLEF',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de California',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('University of East Anglia G.B.',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('SOMEE (Sociedad Mexicana de Estudios Electorales)',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('REVES 15, Universidad de Guadalajara y COLEF',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('The University of the Texas at Austin',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Random House Mondadori',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Raya en el Agua',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Culturas Populares del ICBC',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Latin American Studies Association',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Sonora',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro de Investigación en Alimentación y Desarrollo (CIAD)',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('UIA-Noroeste, El COLEF, CETYS, DIF- municipal, CSPP, Alliant University Children s Hospital',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Suth western College',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Asociación Latino-Iberoamericana de Gestión Tecnológica',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Colegio de Michoacán',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Planned Parethood, Instituto nacional de la mujer y COLEF',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Planned parenthood, de San Diego  Instituto estatal de la mujer de BC y COLEF',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Plan Estratégico de Ciudad Juárez',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro de Estudios Culturales. Museo UABC',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('University Galery',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('IMAFED','Secretaría de Gobernación',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Georgetown University, Washington, DC, Estados Unidos',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad La Sapienza, Roma',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Maestría en Estudios Latinoamericanos',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Tecnológico de Estudios Superiores de Occidente',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Tecnológico y de Estudios Superiores de Occidente',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('XVII Ayuntamiento de Tijuana',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CEPAL-CELADE',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('La Comisión de Cooperación Laboral',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Gobierno de Italia',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidada de Guadalajara',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Pedagógica Nacional',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('El Colegio de México',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Nacional de Salud Pública',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Red Internacional  de Colaboración en las Ciencias del Comportamiento',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Iberoamericana Noroeste',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Southwestem College',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Fundación Mexicana de la Salud',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Zacatecas',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Iberoamericana Noroeste en colaboración con El Colef',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto de Investigaciones Dr. José María Luis Mora',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Organización de Estados Iberamericanos',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma de Baja California Sur',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Scalabrini House of Theology',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('El Colegio de Tamaulipas',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro Panamericano de Humanidades',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad del Noreste de México',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro Comunitario de Salud Mental de Regla',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Whittir College',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Comisión para Prevenir y Erradicar la Violencia Contra las Mujeres en Ciudad Juárez',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Weatherhead Center Harvard University',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Redlands',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma de chihuahua',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Sociedad Cubana de Psiquiatría',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Foro Migraciones',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universite de Nice-Sophia Antipolis',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto de Administración Pública del Estado de Quintana Roo',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro de Estudios Universitarios Xochicalco',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Comisión Ciudadana de Derechos Humanos Noroeste A.C.',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Secretaría de Salud',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma de Yucatán',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Red Internacional de Investigadores en Ciencias Sociales y Humanas',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('ENLACE',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro de Estudios Superiores del Noroeste',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de la Habana',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro Interamericano de Estudios de Seguridad Social',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de La Laguna, Tenerife, España',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro de Investigacines Biológicas del Noroeste',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Trakya University',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('San Diego Natural History Museum',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro de Enseñanza Técnica y Superior',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Politécnico Nacional',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Université de Poitiers',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('El Colegio de San Luis',null,null,null,GETDATE(),null,GETDATE(),1);

insert into Instituciones values('Université d Orléans',null,null,null,GETDATE(),null,GETDATE(),1);

insert into Instituciones values('Universidad Autónoma del Estado de Hidalgo',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('University San Diego',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Consulado de los Estados Unidos',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('University of Pittsburgh',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro de Investigación y Estudios Avanzados-IPN',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Complutense de Madrid',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Milán',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Sin Fronteras',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Rey Juan Carlos',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Woodrow Wilson Center',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Murcia',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma de Madrid',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('COLEF-UABC',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Écoles des Hautes Études en Sciences Sociales (EHESS). Université de Paris, Sorbonne',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Fondo de las Naciones Unidas para la Infancia (UNICEF',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('El Colef, UABC, Universidad de California San Diego, Universidad Estatal de San Diego',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Woodbury University',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Latina de Panamá',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Comisión Interamericana de Mujeres',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('University of Essex',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Seminario Mayor de Nuevo Laredo',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Mexicano de Doctrina Social',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro Fronterizo de Promoción de Derechos Humanos A.C.',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Fundación para el Debido Proceso Legal',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro Nacional para Tribunales Estatales',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Secretaría de Relaciones Exteriores',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Comisión Internacional de Límites y Aguas entre México y Estados Unidos',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Coalición Pro Defensa del Migrante',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Michoacana de San Nicolás Hidalgo',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Washington',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Queretaro',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Rural Services Research Institute',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Cristóbal Colon',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Comisión Económica para América Latina-México',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Institut National de Etude Demogaphiques',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Secretaría de la Comisión de Población',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Sin Fronteras, A.C',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Asuntos Migratorios de la LIX Legislatura de la Cámara de Diputados',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('University of  California, San Diego',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad del Caribe',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Museo de Historia Mexicana',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Consejo Nacional para Prevenir la Discriminación',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('La Comisión Coordinadora y las Instituciones Convocantes',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Sonora, UAS,  UABC, Centro de Investigación en Alimentación y Desarrollo',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Deutscher Akademischer Austauschdienst Servicio Alemán  de Intercambio Académico',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('University of Skovde',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Nacional de Antropología e Historia',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universitat de Valencia',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Facultad de Psicología Universidad de la Habana','Dr. Dionisio Zaldivar Pérez',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto de Investigación e Inversión estrategica del Gobierno de Guanajuato',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Francisco Gavidia',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro de Referencia Latinoamericano para la Educación Especial',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad UNIVER Noroeste',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Tijuana',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universite de Toulouse',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Tecnológico de Ciudad Juárez',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Xochicalco',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Iowa States University',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma del Estado de Morelos',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Gobierno del Estado de Coahuila',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Medical School',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Red de Salud de las Mujeres Latinoamericanas y del Caribe',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Observatorio Ciudadano del Feminicidio',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Valencia',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Michoacana del Oriente',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Tecnológico de Monterrey',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro de Investigaciones y Estudios Superiores en Antropología Social',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('East Carolina University',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Ayuntamiento de Nuevo Laredo','Horacio Garza Garza - Presidente Municipal',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Ayuntamiento de Tijuana','José Guadalupe Osuna Millán - Presidente Municipal',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Barton Aschman Associates','Roberto C. Scales',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CECUT','Alfredo Alvarez - Director General',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CESPT','Ismael Grijalba Palomino - Director General',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CICESE','Mario Martínez García - Director General',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CIESAS','Dr. Raúl Loyola Díaz  - Director General, Lic. Araceli Mercado','relinst@juarez.ciesas.edu.mx',null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CNIME','Humberto Inzunza Fonseca - Presidente','hinzunza@telnor.net',null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('COLMEX','Andrés Lira González - Presidente',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CONACYT','Jaime Martuscelli Quintana - Director Adjunto de Investigación Científica y Secretario Ejecutivo Sup',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('SIREYES','Héctor Menchaca Solís',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CONAGUA','Ing. Guillermo Villalobos - Director General',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CONAPO','Rosa María Ruvalcaba - Directora General de Estudios de Población',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('COPARMEX','Pedro Matín Briones - Presidente',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CUT','Jesús J. Ruiz Barraza - Presidente',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('FLACSO-Guatemala','Dr. René Eduardo Poitevin - Director',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Ford Foundation','No tiene',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('FOSIMAC','Martín L. Celaya Barragan - Secretario Técnico',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('FOSIREYES','Héctor Menchaca Solís',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('FOSIVILLA','Eduardo Hurtado García - Secretario Técnico',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Fundación Friedrich Ebert','Lic. Ekart Wild - Representante',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Gobierno del Estado SCT','Héctor Terán Terán - Gobernador Constitucional de B. C.',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Gobierno del Estado de Chihuahua','Jesús M. Sandoval Armenta - Director General de Fomento Económico',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Federal Electoral','José Woldenberg Karakosky - Consejero Presidente',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('INEGI','Carlos M. Jarque - Presidente',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Tecnológico de la Paz','M.C. Marcelino Bauza Rosete - Director',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('ITPN','Víctor Manuel Ibarra Balderas - Director',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('ISSSTE','Lic. Olimpia Talla Jiménez',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Medicina Social Comunitaria','Blanca Lomelí - Directora',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('New Mexico State University','William Conroy - Presidente',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('SEMARNAP','No tiene',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Nacional de Ecología','Miguel Anguel Cancino Aguilar',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('SDSU','Nancy A. Marlin - Provost and Vicepresidente of Academic Affaris',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('SEBS','M.C. Lorenzo Gómez Morín - Secretario',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('SEDESOL','Lic. Mario Palma Rojo - Subsecretario de Desarrollo Regional',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('SRE','Embajador Jorge Alberto Lozoya - Director Ejecutivo',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('STPS','Lic. Humberto Lugo Gil - Oficial Mayor',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('SOMEDE','Carlos Welti',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('TAMIU','J. Charles Jennet - President',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('UABC','Héctor Everaldo Beltrán Corona - Rector',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma de Coahuila','No tiene',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('UABCS','Jorge Alberto Vale Sánchez - Rector',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Colima','Carlos Salazar Silva - Rector',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autonoma Metropolitana Iztapalapa','Terán Casa Nueva - Rector',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('UIA - Noroeste','Humberto Barquera Gómez - Apoderado',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('WWU','Johm O. Stubbs - President and Vice Chancellor',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('SFU','Johm O. Stubbs - Presidente and Vice Chancellor',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Nacional de Migración','No tiene',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Secretaria de Comercio','Jose Perez','jperez@sc.com',null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma de Guadalajara',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma de Ciudad Juárez',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('S.E.P.',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CREA',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Guadalajara',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('XIII Ayuntamiento de Mexicali',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma de Nuevo León',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Fondo de Cultura Económica',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Miguel Ángel Porrúa',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('UNAM',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('El Colmex',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Secretaría del Trabajo y Previsión Social',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Consejo Nacional de Población',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Asociacón Latinoamericana de Sociología',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('ORSTOM',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Consejo Estatal de Población de Oaxaca',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('ITESO',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Chicana/Latina Research Center-UCD',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Plaza y Valdez',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Iberoamericana',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Programa Cultural de las Fronteras',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Conaculta',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('IRD',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Wisconsin','Alberto Palloni',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Iberomericana Santa Fé',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Consorcio transfronterizo de investigación en Acción',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro de investigación y Docencia Económica',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('University of Texas',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Fundación Rockefeler',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Fondo Nacional para la Cultura y las Artes',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Procuraduría Federal de Protección al Ambiente',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Consejo de Desarrollo Económico de Tijuana',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Organización Panamericana de la Salud Ely Lilly',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Programa Interdisciplinario de Estudios de la Mujer (PIEM)',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Fundación Mac Arthur',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Secretaría de Gobernación',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('UC Mexus',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('SAHOPE',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('University of Southern California',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Comisión de Cooperación Ambiental México-Estados Unidos',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Sistema de Investigación Francisco Villa',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Comisión de Cooperación Económica Fronteriza (COCEF)',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Organización Franco y Asociados',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Municipio de Juarez, Chihuahua',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Junta Municipal de Agua y Saneamiento',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('SIMAC',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('University of California, in Santa Cruz, Ca.',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Parsons Transportation Group','Thomas E. Barron',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Colegio de Postgraduados',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('COESPO-GUANAJUATO','DR. LUIS FERNANDO MACIAS GARCIA',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('HEWLETT FOUNDATION',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('USC',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('AIDS RESEARCH PROGRAM',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('USAID',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('El Colef',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Comisión de Cooperación Ecologica',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('The Border Studies Program',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Secretaría de Energía de la Federación',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Institut De Recherche Pour Le Development',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Compton Foundation',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('San Diego State University',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('International Community Foundation',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('COESPO ( SONORA )',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Baker & Associates, energy Consultants',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Nacional de Nutrición',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CDT de Tecate',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Fundación El Colef',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Municipio de San Pedro Garza Garcia Nuevo León',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('El Colegio Mexiquense','Iracheta Cenecorta Alfonso Xavier',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Mexicano de Seguro Social','David Ontiveros',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Environmental Resources Management',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Camp Dresser & Mckee Inc.',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Fideicomiso','Ramiro Moreno Navarro',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Subsecretaria de asuntos religiosos en la Sec. de Gobernación',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('SEMPRA ENERGY MEXICO',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Dir. Gral. Finanzas del Gobierno de Chihuahua',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Estatal de Michigan','Scott Whiteford',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Mexicano del Seguro Social','David Ontiveros',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Cuentas Bancarias','Ramiro Moreno Navarro',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('FLACSO - MEXICO',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Tecnológico y de Estudios Superiores de Monterrey',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Tecnológica de Matamoros',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro Universitario del Noreste',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Municipal de Planeación',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Comisión para Asuntos de la Frontera Norte',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Archivo General del Estado de Nuevo León',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Texas El Paso',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('UAM',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Secretaría de Desarrollo Urbano y Obras Públicas del Gobierno del Estado de Nuevo León',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Consejo Estatal de Población',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CONARTE',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Otro',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('International Community Foundation San Diego, Ca.','Richard Kiy',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto de Cultura de Baja California',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Southwestern College',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Pacific Sociological association',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('ITAM',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autonoma de Sinaloa',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('St Josephs Inivercity',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Loyola Marymount University',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Fairfiled University',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('LaSalle University',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('John Carrol University',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Monterrey',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('El Colegio de Michoacán',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma de Tamaulipas',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Tecnológico de Nuevo Laredo',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Interamericana del Norte',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Museo Casamata',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro de Investigación en Materiales Avanzados (CIMAV)','David Ríos Jara',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('St. Josephs University',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Layola College',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('University  of Notre Dame',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Institut Natinal Du Travail de Emploi et de la formation professionnelle',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma Metropolitana-Xochimilco',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Gabriel Zzekely Sánchez',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Quitar Juarez',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Banco de México',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CIAD',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autonoma del Estado de México',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('INESER',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('El Colegio de Sonora',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Guanajuato',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('nada tijuana',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro Regional de Investigación Multidisciplinaria CRIM',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma de Puebla (UAP)',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('INSP',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('INSAD',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro de Estudios México- Estados Unidos','Universidad de California en San Diego',null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto de Altos Estudios Internacionales',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Escuela Nacional de Antropología e Historia. Unidad Chihuahua',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Casa del Migrante en Tijuana, Centro Scalabrini',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Colegio de Michoacan',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Planned parethood, Instituto estatal de la mujer  de BC y COLEF',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma de Baja California',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CIDE',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Tijuana Trabaja',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de San Francisco',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Planned parethood de San Diego, Instituto estatal de la mujer de BC y COLEF',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Hosei University',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CREDAL, COLEF e ITESM',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Grupo Editorial EON',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autonóma Agraria Antonio Narro (UAAAN)',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('University of California, San Diego (UCSD)',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('The University of California',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('The University of California and El Colegio de la Frontera Norte',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Estatal de San Diego',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Red nacional  de colaboración en las ciencias del comportamiento',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('CETYS-Universidad',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma de Sinaloa',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Barcelona',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Plaza & Janés',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('IMAC',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Escuela Normal Fronteriza',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('INSITE',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Department of chicana chicano studies',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Harvard University',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('UPN',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto Nacional de Desarrollo Social',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('UABC Ensenada',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Secretaría de Desarrollo Social',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad de Guadalajara y El COLEF',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Fondo Poblacional de Naciones Unidas',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Universidad Autónoma Metropolitana-Iztapalapa',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Centro de Estudios Estratégicos para el Desarrollo',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('COLEF - CICESE',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Instituto de la Mujer para el Estado de Baja California',null,null,null,GETDATE(),null,GETDATE(),1);
insert into Instituciones values('Arizona State University',null,null,null,GETDATE(),null,GETDATE(),1);

insert into TipoParticipaciones values('Ponente',null,GETDATE(),null,GETDATE(),1);
insert into TipoParticipaciones values('Comentarista',null,GETDATE(),null,GETDATE(),1);
insert into TipoParticipaciones values('Moderador',null,GETDATE(),null,GETDATE(),1);
insert into TipoParticipaciones values('Coordinador de Mesa',null,GETDATE(),null,GETDATE(),1);
insert into TipoParticipaciones values('Organizador',null,GETDATE(),null,GETDATE(),1);
insert into TipoParticipaciones values('Coorganizador',null,GETDATE(),null,GETDATE(),1);

insert into TipoActividades values('Investigación',null,GETDATE(),null,GETDATE(),1);
insert into TipoActividades values('Docencia',null,GETDATE(),null,GETDATE(),1);
insert into TipoActividades values('Vinculación',null,GETDATE(),null,GETDATE(),1);

insert into TipoCapitulos values('Capitulo con arbitraje',null,GETDATE(),null,GETDATE(),1);
insert into TipoCapitulos values('Capitulo sin arbitraje',null,GETDATE(),null,GETDATE(),1);
insert into TipoCapitulos values('Capitulo traducido a otro idioma',null,GETDATE(),null,GETDATE(),1);
insert into TipoCapitulos values('Ponencia publicada',null,GETDATE(),null,GETDATE(),1);
  
insert into FormaParticipaciones values('Editor',null,GETDATE(),null,GETDATE(),1);
insert into FormaParticipaciones values('Compilador',null,GETDATE(),null,GETDATE(),1);
insert into FormaParticipaciones values('Coordinador',null,GETDATE(),null,GETDATE(),1);

insert into TipoParticipantes values('Persona Fisica',null,GETDATE(),null,GETDATE(),1);
insert into TipoParticipantes values('Investigador',null,GETDATE(),null,GETDATE(),1);


--Faltan todavia los investigadores externos
insert into InvestigadorExternos values('Acevedo Gladys',null,null,null,GETDATE(),null,GETDATE(),1);